#theme: jekyll-theme-minimal
#title: 'Mai La's Portfolio'
#description: Website for Showcasing my Data Science Projects
#logo: ./images/BerkeleyBackground.jpg
permalink: /blog/:year/:month/:day/:title
markdown: kramdown

theme: jekyll-theme-minimal