---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: project
  labels:
    app: project
spec:
  template:
    spec:
      containers:
        - name: project
          image: project
          resources:
            requests:
              cpu: 500m
              memory: 1500Mi
            limits:
              cpu: 1000m
              memory: 1500Mi
          imagePullPolicy: IfNotPresent
          env:
            - name: REDIS_URL
              value: "redis://redis:6379"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 1
            periodSeconds: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20
